### ISSUE TITLE
Can't see the text on the backend

### ISSUE THREAD

**Issue by nickhamze** [sortabrilliant/spoiler-alert#1]
On the backend once I add the style I can't see the text anymore.

<img width="866" alt="screen shot 2018-11-30 at 7 14 52 pm" src="https://user-images.githubusercontent.com/158918/49322371-7819c900-f4d4-11e8-8d51-2118da2e17f3.png">

**Comment by jrtashjian** [comment]
Fixed in 2574f7f7fd36731d58aed1be28b9759d9e94f3cd
