### ISSUE TITLE
General Maintenance 

### ISSUE THREAD

**Issue by nickhamze** [sortabrilliant/spoiler-alert#10]
The plugins seems to work ok (double check if you can) but it needs a little maintenance.

- Removing legacy Github updater code
- Updating package.json to remove vulnerable dependencies
- Add blocks.json following the instructions here (https://github.com/WordPress/wporg-plugin-guidelines/blob/block-guidelines/blocks.md#4-block-plugins-must-include-a-blockjson-file)

**Comment by jrtashjian** [comment]
Updates made. A `blocks.json` file is not needed since this is just adding custom styles to existing blocks.
