### ISSUE TITLE
How do you deselect styles?

### ISSUE THREAD

**Issue by nickhamze** [sortabrilliant/spoiler-alert#2]
This also brings up an issue that effects Ghostwriter as well but how do you remove styles?

Do we need to add a no style option? I thought that if I clicked on the style again it would remove it but it seems like once I add the style I can't unselect it.

**Comment by nickhamze** [comment]
Found a similar issue in the Gutenberg issues:
https://github.com/WordPress/gutenberg/issues/11613

**Comment by jrtashjian** [comment]
It looks like if there are multiple styles defined exactly the same, no errors are thrown within Gutenberg. We'll just have to remove our own default once the UX is fixed in Gutenberg.

**Comment by jrtashjian** [comment]
Resolved in 4799ddb21259a54b9c11ba3fa096768692a6b62f.
