### ISSUE TITLE
Display issues

### ISSUE THREAD

**Issue by nickhamze** [sortabrilliant/spoiler-alert#3]
Do we need the spoiler effects on the backend? It just seems to get in the way when working with the content. Is there someway we can illustrate that this is spoiler content without covering it up?

Maybe something as simple as a badge in the corner:
![example](https://user-images.githubusercontent.com/158918/49324254-def8ab80-f4ef-11e8-8acc-414b4b298500.png)

Also in the front end CSS can we remove this:
"font-family: sans-serif;"

I want it to blend in as much as possible and without this it should just inherit whatever the body font is.

Can we also reduce the padding a tad so it doesn't break on to two lines on mobile:
<img width="299" alt="screen shot 2018-11-30 at 10 29 27 pm" src="https://user-images.githubusercontent.com/158918/49324238-7d384180-f4ef-11e8-80f0-5e82cf943745.png">

**Comment by nickhamze** [comment]
Can we also change the color to just plain black? i think it will look better on a variety of sites if it was all black instead of a bit gray.

**Comment by jrtashjian** [comment]
Here's what I've put together for the badge. It follows the block outline/label design you see when hovering over blocks in the editor. The label hides as soon as you hover or select the block. I think the consistency here works best. Having the badge in another corner looked out of place.

![screenshot_2018-12-01 edit post wordpress local wordpress](https://user-images.githubusercontent.com/375788/49330109-21ee6980-f558-11e8-8f7f-33181d7dc66e.png)

**Comment by nickhamze** [comment]
Cool, looks good.

**Comment by jrtashjian** [comment]
All resolved in: bf4b2658235aec40b4aa759de28e3670e7188cbc
